### ISSUE TITLE
Replace memory cache with a database

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry-holding/edgex-ui-go#12]
here : https://github.com/badboy-huaqiao/edgex-ui-go/blob/master/cache.go#L24

**Comment by yanghua** [comment]
MongoDB maybe a temp candidate. what's your opinion? Or some lightweight Embedded Database which does not need to install independently?

cc @tsconn23 @jpwhitemn and @drasko

**Comment by badboy-huaqiao** [comment]
it has been finished,it should be closed now,
