### ISSUE TITLE
ID field is displayed as a truncated value

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry-holding/edgex-ui-go#126]
The ID field is displayed truncated, but the EdgeX API is not able to find via truncated IDs, it needs exact IDs.

**Comment by brandonforster** [comment]
There is a shortened ID field on:

Gateway
Device
Device Service
Device Profile
Export
Rule Engine

**Comment by badboy-huaqiao** [comment]
@brandonforster ok, assign it to me , i know the reason

**Comment by brandonforster** [comment]
@badboy-huaqiao I don't have permissions on this project to assign.

**Comment by badboy-huaqiao** [comment]
@brandonforster ok, i assign it to myself

**Comment by badboy-huaqiao** [comment]
i have fixed , i close it now
